# Generated by Django 3.2.5 on 2021-07-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=254)),
                ('pdate', models.DateField(max_length=50)),
                ('pdept', models.CharField(choices=[('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Medical Reasearch', 'Medical Reasearch')], default='Select', max_length=20)),
                ('pcontact', models.CharField(max_length=15)),
                ('pmsg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Patientinfo',
            },
        ),
    ]
